<a href="https://colab.research.google.com/github/mansoorkhan1999/mansoorkhan1999/blob/main/COLAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
b=np.arange(12).reshape(4,3)

In [ ]:
b


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
b.max(axis=0)


array([ 9, 10, 11])

In [ ]:

f=int(input('Enter number '))
for i in range(f):
   i=f%2
   print (i)
   
    


Enter number 11
1
1
1
1
1
1
1
1
1
1
1


In [ ]:
a=input('Enter Strings : ')
stack=[]
for ch in a:
  if(stack and ch==stack[-1]):
    stack.pop()
  else: 
    stack.append(ch)
print(stack)


Enter Strings : aacaacs
['s']


In [ ]:
a

'asssbc'

In [ ]:
from collections import deque


In [ ]:
from collections import deque
T=deque()
S = deque()
num=int(input('Enter how many number  '))

for i in range(num):
  T.append(i)
while (len(T)!=0):
  S.append(T.pop())
print(S)

from collections import deque
T=deque()
S = deque()
def transfer(self,self):
    for i in range(num):
       T.append(i)
    while (len(T)!=0):
       S.append(T.pop())`



Enter how many number  9
deque([8, 7, 6, 5, 4, 3, 2, 1, 0])


In [ ]:
def reverse_list(S):
    temp = Stack()
    for e in S:
        temp.push(e)
    
    for i in range(len(S)):
        S[i] = temp.pop()

lists = [[1,2,3,4,5,6],
        [3,2,5,6,7,8,9,5],
        [9,8,7,6,5,4,3,2,1]]

for l in lists:
    print ('Before: ', l)
    reverse_list(l)
    print('After:  ', l)
    print()


deque([])


In [ ]:
from collections import deque
counter =0
stack=deque()
wstr=input("Enter string")
for item in wstr :
  if (item=='('or item=='['or item=='{'):
    stack.append(item)
    

  elif(item==')'or item==']'or item=='}'):
    stack.pop()
    
if stack[]:
  print("Balanced")
else :
  print("Unbalanced")


Enter string{}


NameError: ignored

In [ ]:
string=input("Enter a string to check Palendrom")
string2=""
stack=[]
for i in string:
 stack.append(i)
while len(stack)!=0:
 string2=string2+stack.pop()
if(string2==string):
 print("The entered string is Palendrom")
else:
 print("The entered string is not a Palendrom")

Enter a string{))
The entered string is not a Palendrom


In [ ]:
def arePairs(open,close):
    if open=='[' and close==']':
        return True
    if open=='{' and close=='}':
        return True
    if open=='(' and close==')':
        return True
    return False
def Balanced(A):
    stack=[]
    for i in range(len(A)):
        if A[i]=='[' or A[i]=='{' or A[i]=='(':
            stack.append(A[i])
        elif A[i] == ']' or A[i] == '}' or A[i] == ')':
            if arePairs(stack[-1],A[i] or len(stack)!=0 ):
                stack.pop()
            else :
                return False
    if len(stack)==0:
        return True
        print("Balanced ")
    else:
        return False
        print("UnBalanced")

A=input("Enter Parenthesis : ")
print(Balanced(A))


Enter Parenthesis : ))(


IndexError: ignored

In [ ]:
hi import numpy as np
class nump:
 def __init__(self):
      self.list=np.arange(10)
 def enqueue(self,data):
      n=np.append(self.list,data)
      return n
 def dequeue(self):
    np.delete(self.list,0)
 def front(self):
    return self.list[0]
 def rear(self):
    return self.list[-1]
 def isempty(self):
    if (len(self.list)==0):
      return True
    else:
      return False
 def length(self):
    return len(self.list)
 def display(self):
    return self.list

R-6.1 What values are returned during the following series of stack operations, if
executed upon an initially empty stack? push(5), push(3), pop(), push(2),
push(8), pop(), pop(), push(9), push(1), pop(), push(7), push(6), pop(),
pop(), push(4), pop(), pop().

***ANS***
Operations performed according to the quetion are given below:

1) Push(5):
        When stack is empty and we execute function **Push(5)** then it push 5 into the empty stack and now the top is 5.

2) Push(3):
       After Push(5) operation when we execute **Push(3) **operation then it push 3 into the stack and now the top is 3. 

3) POP():
       When **pop()** function executed then it first retrieve/fetch top value after that  delete that top value means it delete last value that push into stack means it delete 3 and now the top is 5.After pop it returns 3.

4) Push(2):
       After pop when we Push(2) then it push 2 into the stack and now the top is 2.

5) Push(8):
       After Push(2) function when we Push (8) then it append 8 into the stack and now the top is 8. Now in stack there are three values 5,2,8.

6) POP():
       When call function pop() then it fetch the top value 8 and delete the value 8. And now there are 5 and 2 are left in stack where 2 is Top.After pop() it returns 8.

7) POP():
      After Pop() again it returns 2 and now the top is 5.

8) Push(9):
      After Push(9) then it append 9 into the stack and now the top is 9. And now there is 5 and 9 in the stack.

9) Push(1):
      After Push(1) then it append 1 into the stack and now the top is 1. And now there is 5,9 and 1 values in the stack.

10) Pop():
      After pop() it delete top value 1 from stack and now there are 5 and 9 two values left in stack and 9 is top now.

11) Push(7):
      After push(7) it append 7 into the stack and now there is three values in the stack 5,9,7 and 7 is top now.

12) Push(6):
       After push(6) it append 6 into the stack and now there is four values in the stack 5,9,7,6 and 6 is top now.

13) Pop():
       When we pop from current stack which is 5,9,7,6 than it delete the top value 6 from stack.

14) Pop():
       After pop() again it delete top value 7 .

15) Push(4):
       After push(4) it append 4 in stack and now top is 4 and there are three values in stack 5,9,4.

16) Pop():
       Calling pop function it returns 4 and delete 4 from stack.

17) Pop():
      Calling pop function it returns 9 and delete 9 from stack because it is top. 


                               ------------

And after perform all operations now there is one value left in stack which is 5 and it is top now.


R-6.2 Suppose an initially empty stack S has executed a total of 25 push operations, 12 top operations, and 10 pop operations, 3 of which raised Empty errors that were caught and ignored. What is the current size of S?

ANS:
25 pushes = 25 index

10 pops = 25 - 10 = 15

3 pops rise empty errors and didn't change size of stack means only 7 pops occur changes = 25-7  = 18

tops does not matter, so it should be 18`

In [ ]:
def arePairs(open,close):
    if open=='[' and close==']':
        return True
    if open=='{' and close=='}':
        return True
    if open=='(' and close==')':
        return True
    return False

def Balanced(A):
    stack=[]
    for i in range(len(A)):
        if A[i]=='[' or A[i]=='{' or A[i]=='(':
            stack.append(A[i])
        elif A[i] == ']' or A[i] == '}' or A[i] == ')':
            if arePairs(stack[-1],A[i]):
                stack.pop()
            else:
               return False
    if len(stack)==0:

        print("Balanced")
    else:
        print("Unbalanced")


A=input("Enter Parenthesis : ")
print(Balanced(A))

Enter Parenthesis : ((
Unbalanced
None


In [ ]:
q = queue()

q.display()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
q.enqueue(5)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 5])

In [ ]:
q.dequeue()
q.display()

array([0, 1, 2, 3, 4])

In [ ]:
#Clear Deleting Node
class node:
  def __init__(self,data=None):
    self.data= data
    self.next=None
    
class linkedlist:
  def __init__(self):
    self.head=node()
  def append(self,data):
    new_node=node(data)
    curr=self.head
    while curr.next!=None:
      curr=curr.next
    curr.next=new_node
  def delete(self): 
   temp = self.head
   while temp.next.next:
    secondlast = temp.next
    temp = temp.next
   temp.next = None

  print("All nodes are deleted successfully.")  
  def display(self):
    curr=self.head
    dis=[]
    while curr.next!=None:
      curr=curr.next
      dis.append(curr.data)
    print(dis)

my_list=linkedlist()
my_list.append(2)
my_list.append(3)
my_list.delete()

my_list.display()

All nodes are deleted successfully.
[2]


In [3]:
#Clear Insert at any index
class Node:
  def __init__(self, data):
    self.data = data
    self.next = None


class LinkedList:
  def __init__(self):
    self.head = None

  #Add new element at the end of the list
  def push(self, newElement):
    newNode = Node(newElement)
    if(self.head == None):
      self.head = newNode
      return
    else:
      temp = self.head
      while(temp.next != None):
        temp = temp.next
      temp.next = newNode

 
  def push_at(self, newElement, position):     
    newNode = Node(newElement) 
    if(position < 1):
      print("\nposition should be >= 1.")
    elif (position == 1):
      newNode.next = self.head
      self.head = newNode
    else:    
      temp = self.head
      for i in range(1, position-1):
        if(temp != None):
          temp = temp.next   
      if(temp != None):
         newNode.next = temp.next
         temp.next = newNode  
      else:
        print("\nThe previous node is null.")

  
  def PrintList(self):
    temp = self.head
    if(temp != None):
      print("The list contains:", end=" ")
      while (temp != None):
        print(temp.data, end=" ")
        temp = temp.next
      print()
    else:
      print("The list is empty.")

               
MyList = LinkedList()


MyList.push(10)
MyList.push(20)
MyList.PrintList()

no=input("Enter a value ")
num=int(input("Enter a index "))
MyList.push_at(no, num)
MyList.PrintList()  

The list contains: 10 20 
Enter a value 23
Enter a index 2
The list contains: 10 23 20 


In [7]:
#Clear Append right and Append left
class Node:
  def __init__(self, data):
    self.data = data
    self.next = None

#class Linked List
class LinkedList:
  def __init__(self):
    self.head = None

  #Append right
  def push(self, newElement):
    newNode = Node(newElement)
    if(self.head == None):
      self.head = newNode
      return
    else:
      temp = self.head
      while(temp.next != None):
        temp = temp.next
      temp.next = newNode  

  #Append left
  def push_front(self, newElement):

    newNode = Node(newElement)
    newNode.next = self.head 
    self.head = newNode   

  #display the content of the list
  def PrintList(self):
    temp = self.head
    if(temp != None):
      print("The list contains:", end=" ")
      while (temp != None):
        print(temp.data, end=" ")
        temp = temp.next
      print()
    else:
      print("The list is empty.")

# test the code                  
MyList = LinkedList()

#Add three elements at the start of the list.
MyList.push_front(10)
MyList.push_front(20)
MyList.push_front(30)
MyList.push(50)

MyList.PrintList()

The list contains: 30 20 10 50 
